keyboard:
  matrix_positions:
    # Left Hand
    # Pinky (columns 1-3)
    - [[2,1],  [1,2],  [2,2],  [3,2],  [2,3],    # Left pinky (north, west, center, east, south)
    # Ring (columns 4-6)
      [5,1],  [4,2],  [5,2],  [6,2],  [5,3],    # Left ring
    # Middle (columns 7-9)
      [8,1],  [7,2],  [8,2],  [9,2],  [8,3],    # Left middle
    # Index (columns 10-12)
      [11,1], [10,2], [11,2], [12,2], [11,3],   # Left index
    # Right Hand
    # Index (columns 13-15)
      [14,1], [13,2], [14,2], [15,2], [14,3],   # Right index
    # Middle (columns 16-18)
      [17,1], [16,2], [17,2], [18,2], [17,3],   # Right middle
    # Ring (columns 19-21)
      [20,1], [19,2], [20,2], [21,2], [20,3],   # Right ring
    # Pinky (columns 22-24)
      [23,1], [22,2], [23,2], [24,2], [23,3]]   # Right pinky

    # Thumb clusters (5 keys each: P, N, K, D, U)
    - [[2,4],  [3,4],  [4,4],  [5,4],  [6,4],             # Left thumb cluster (P, N, K, D, U)
      [20,4], [21,4], [22,4], [23,4], [24,4]]            # Right thumb cluster (P, N, K, D, U)

  positions:
    # Left Hand
    # Pinky (columns 1-3)
    - [[2,1],  [1,2],  [2,2],  [3,2],  [2,3],    # Left pinky (north, west, center, east, south)
    # Ring (columns 4-6)
      [5,1],  [4,2],  [5,2],  [6,2],  [5,3],    # Left ring
    # Middle (columns 7-9)
      [8,1],  [7,2],  [8,2],  [9,2],  [8,3],    # Left middle
    # Index (columns 10-12)
      [11,1], [10,2], [11,2], [12,2], [11,3],   # Left index
    # Right Hand
    # Index (columns 13-15)
      [14,1], [13,2], [14,2], [15,2], [14,3],   # Right index
    # Middle (columns 16-18)
      [17,1], [16,2], [17,2], [18,2], [17,3],   # Right middle
    # Ring (columns 19-21)
      [20,1], [19,2], [20,2], [21,2], [20,3],   # Right ring
    # Pinky (columns 22-24)
      [23,1], [22,2], [23,2], [24,2], [23,3]]   # Right pinky

    # Thumb clusters (5 keys each: P, N, K, D, U)
    - [[2,4],  [3,4],  [4,4],  [5,4],  [6,4],             # Left thumb cluster (P, N, K, D, U)
      [20,4], [21,4], [22,4], [23,4], [24,4]]            # Right thumb cluster (P, N, K, D, U)

  hands:
    # Main key rows (rows 1-3)
    - [Left, Left, Left, Left, Left,      # Left pinky positions
       Left, Left, Left, Left, Left,      # Left ring positions
       Left, Left, Left, Left, Left,      # Left middle positions
       Left, Left, Left, Left, Left,      # Left index positions
       Right, Right, Right, Right, Right, # Right index positions
       Right, Right, Right, Right, Right, # Right middle positions
       Right, Right, Right, Right, Right, # Right ring positions
       Right, Right, Right, Right, Right] # Right pinky positions

    # Thumb row (row 4)
    - [Left, Left, Left, Left, Left,            # Left thumb cluster (5 keys)
       Right, Right, Right, Right, Right]      # Right thumb cluster (5 keys)

  fingers:
    - [Pinky, Pinky, Pinky, Pinky, Pinky,   # Left pinky positions
       Ring, Ring, Ring, Ring, Ring,         # Left ring positions
       Middle, Middle, Middle, Middle, Middle, # Left middle positions
       Index, Index, Index, Index, Index,     # Left index positions
       Index, Index, Index, Index, Index,     # Right index positions
       Middle, Middle, Middle, Middle, Middle, # Right middle positions
       Ring, Ring, Ring, Ring, Ring,         # Right ring positions
       Pinky, Pinky, Pinky, Pinky, Pinky]   # Right pinky positions

    # Thumb row (row 4)
    - [Thumb, Thumb, Thumb, Thumb, Thumb,           # Left thumb cluster (5 keys)
       Thumb, Thumb, Thumb, Thumb, Thumb]           # Right thumb cluster (5 keys)

  key_costs:
      # N    W   C   E   S
      - [5,  6,  3,  5,  3,     # Left pinky
        4,   8,  2,  5,  2,     # Left ring
        4,   7,  2,  5,  2,     # Left middle
        4,   5,  2,  4,  2,     # Left index
        4,   4,  2,  5,  2,     # Right index
        4,   5,  2,  7,  2,     # Right middle
        4,   5,  2,  8,  2,     # Right ring
        5,   5,  3,  6,  3]     # Right pinky

      # Thumb row (row 4)
      - [2, 2, 3, 2, 2,         # Left thumb cluster (P, N, K, D, U)
        2, 2, 3, 2, 2]         # Right thumb cluster (P, N, K, D, U)

  unbalancing_positions:
    # Main key rows (rows 1-3) - [N, W, C, E, S] per finger
    - [[0, 2], [3, 0], [0, 0], [2, 0], [0, 0],     # Left pinky (N, W, C, E, S) - W is outward (hardest)
      [0, 1], [5, 0], [0, 0], [1, 0], [0, 0],     # Left ring (N, W, C, E, S) - W is outward (harder)
      [0, 1], [1, 0], [0, 0], [1, 0], [0, 0],     # Left middle (N, W, C, E, S) - W is outward
      [0, 1], [1, 0], [0, 0], [1, 0], [0, 0],     # Left index (N, W, C, E, S) - W is outward
      [0, 1], [1, 0], [0, 0], [1, 0], [0, 0],     # Right index (N, W, C, E, S) - E is outward
      [0, 1], [1, 0], [0, 0], [1, 0], [0, 0],     # Right middle (N, W, C, E, S) - E is outward
      [0, 1], [1, 0], [0, 0], [5, 0], [0, 0],     # Right ring (N, W, C, E, S) - E is outward (harder)
      [0, 2], [2, 0], [0, 0], [3, 0], [0, 0]]     # Right pinky (N, W, C, E, S) - E is outward (hardest)

    # Thumb row (row 4)
    - [[0, 0], [0, 0], [0, 2], [0, 0], [0, 5],             # Left thumb cluster (5 keys)
      [0, 0], [0, 0], [0, 2], [0, 0], [0, 5]]             # Right thumb cluster (5 keys)

  symmetries:
    # Main key rows (rows 1-3)
    - [1, 2, 3, 4, 5,         # Left pinky
      6, 7, 8, 9, 10,        # Left ring
      11, 12, 13, 14, 15,    # Left middle
      16, 17, 18, 19, 20,    # Left index
      20, 19, 18, 17, 16,    # Right index (mirrored)
      15, 14, 13, 12, 11,    # Right middle (mirrored)
      10, 9, 8, 7, 6,        # Right ring (mirrored)
      5, 4, 3, 2, 1]         # Right pinky (mirrored)

    # Thumb row (row 4)
    - [21, 22, 23, 24, 25,        # Left thumb cluster (5 keys)
      25, 24, 23, 22, 21]        # Right thumb cluster (mirrored)

  finger_resting_positions:
    Left:
      Pinky: [50.5, 115.5]
      Ring: [100.5, 115.5]
      Middle: [150.5, 115.5]
      Index: [200.5, 115.5]
      Thumb: [230.5, 210.5]
    Right:
      Pinky: [650.5, 115.5]
      Ring: [600.5, 115.5]
      Middle: [550.5, 115.5]
      Index: [500.5, 115.5]
      Thumb: [470.5, 210.5]

  plot_template: |2
                LEFT HAND                                                            RIGHT HAND

       {{0}}        {{5}}          {{10}}          {{15}}                                    {{20}}        {{25}}          {{30}}          {{35}}
     {{1}} {{2}} {{3}}    {{6}} {{7}} {{8}}      {{11}} {{12}} {{13}}      {{16}} {{17}} {{18}}                                {{21}} {{22}} {{23}}    {{26}} {{27}} {{28}}      {{31}} {{32}} {{33}}      {{36}} {{37}} {{38}}
       {{4}}        {{9}}          {{14}}          {{19}}                                    {{24}}        {{29}}          {{34}}          {{39}}


                                          LEFT THUMB             RIGHT THUMB
                                          {{40}} {{43}} {{41}}             {{46}} {{48}} {{45}}
                                             {{44}} {{42}}                 {{47}} {{49}}

  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Main finger clusters (40 keys total)
    - [
        # Left Pinky (North, West, Center, East, South)
        ["q", "", "", "Q"],               # North
        ["", "", "", ""],                 # West (Ctrl modifier placeholder)
        ["c", "", "", "C"],               # Center
        ["`", "", "", "~"],               # East
        ["p", "", "", "P"],               # South

        # Left Ring (North, West, Center, East, South)
        ["b", "9", "", "B"],               # North
        ["", "", "", ""],                 # West (Alt/Option modifier placeholder)
        ["s", "6", "", "S"],               # Center
        ["=", "", "", "+"],               # East
        ["f", "3", "", "F"],               # South

        # Left Middle (North, West, Center, East, South)
        ["k", "8", "", "K"],               # North
        ["", "", "", ""],                 # West (Symbols modifier placeholder)
        ["n", "5", "", "N"],               # Center
        ["v", "", "", "V"],               # East
        ["l", "2", "", "L"],               # South

        # Left Index (North, West, Center, East, South)
        ["g", "7", "", "G"],               # North
        ["", ".", "", ""],                 # West (Shift modifier placeholder)
        ["t", "4", "", "T"],               # Center
        ["h", "0", "", "H"],               # East
        ["d", "1", "", "D"],               # South

        # Right Index (North, West, Center, East, South)
        [".", "", "&", ":"],               # North
        ["-", "", "(", "_"],               # West
        ["a", "", "$", "A"],               # Center
        ["", "", ")", ""],                 # East (Shift modifier placeholder)
        ["u", "", "!", "U"],               # South

        # Right Middle (North, West, Center, East, South)
        [",", "", "*", ";"],               # North
        ["/", "", "[", "\\"],               # West
        ["e", "", "%", "E"],               # Center
        ["", "", "]", ""],                 # East (Numbers modifier placeholder)
        ["o", "", "@", "O"],               # South

        # Right Ring (North, West, Center, East, South)
        ["j", "", "-", "J"],               # North
        ["'", "", "{", "\""],              # West
        ["i", "", "^", "I"],               # Center
        ["", "", "", ""],                 # East (Alt/Option modifier placeholder)
        ["y", "", "#", "Y"],               # South

        # Right Pinky (North, West, Center, East, South)
        ["x", "", "+", "X"],               # North
        ["z", "", "<", "Z"],               # West
        ["m", "", "|", "M"],               # Center
        ["", "", ">", ""],                 # East (Ctrl modifier placeholder)
        ["w", "", "?", "W"]                # South
      ]

    # Thumb clusters (10 keys total: 5 per hand)
    - [
        # Left Thumbs (5 keys: P, N, K, D, U)
        ["r", "", "", "R"],                   # Thumb P - R key
        ["⇥", "⇥", "⇥", "⇥"],              # Thumb N - Tab key
        ["⎋", "⎋", "⎋", "⎋"],              # Thumb K - Escape key
        ["", "", "", ""],                     # Thumb D - Layer 2 (Symbols) modifier (hold)
        ["", "", "", ""],                     # Thumb U - Layer 1 (Numbers) modifier (hold)

        # Right Thumbs (5 keys: P, N, K, D, U)
        ["␣", "", "", "␣"],                   # Thumb P - Space key
        ["↵", "↵", "↵", "↵"],              # Thumb N - Return key
        ["⇪", "⇪", "⇪", "⇪"],              # Thumb K - Caps Lock
        ["", "", "", ""],                     # Thumb D - Layer 1 (Numbers) modifier (hold)
        ["", "", "", ""]                      # Thumb U - Layer 2 (Symbols) modifier (hold)
      ]

  fixed_keys:
    # Main key rows - optimize letters on Layer 0 only, fix modifiers
    - [false, true,  false, false, false,     # Left pinky (fix Ctrl)
       false, true,  false, false, false,     # Left ring (fix Alt/Option)
       false, true,  false, false, false,     # Left middle (fix Symbols modifier)
       false, true,  false, false, false,     # Left index (fix Shift modifier)
       false, false, false, true,  false,     # Right index (fix Shift modifier)
       false, false, false, true,  false,     # Right middle (fix Numbers modifier)
       false, false, false, true,  false,     # Right ring (fix Alt/Option)
       false, false, false, true,  false]     # Right pinky (fix Ctrl)

    # Thumb row - optimize R and Space on Layer 0, fix everything else
    - [false, true, true, true, true,         # Left thumb cluster (R=optimize, Tab=fix, Esc=fix, Symbols=fix, Numbers=fix)
       false, true, true, true, true]         # Right thumb cluster (Space=optimize, Return=fix, Caps=fix, Numbers=fix, Symbols=fix)

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: [1, 2, 3] # only optimize the main layer

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 1

  # Multi-layer modifier configuration
  modifiers:
    # Layer 1: Numbers (numbers on left hand, modifier on right thumb)
    - Right:
        type: hold
        value: [[23, 4]]   # Right Thumb D

    # Layer 2: Symbols (symbols on right hand, modifier on left thumb)
    - Left:
        type: hold
        value: [[5, 4]]   # Left Thumb D

    # Layer 3: Shift (Uppercase - accessible from either hand)
    - Left:
        type: hold
        value: [[10, 2]]   # Left Index West
      Right:
        type: hold
        value: [[15, 2]]   # Right Index East
