metrics:
  # layout metrics

  kla_home_key_words:
    enabled: false
    weight: 500.0
    normalization:
      type: weight_all
      value: 1.0
    params:
      words_filename: "./corpora/english-words-30000.csv"
      min_word_length: 3
      home_row_positions:
        - [2, 2]
        - [3, 2]
        - [4, 2]
        - [5, 2]
        - [14, 2]
        - [15, 2]
        - [16, 2]
        - [17, 2]

  kla_same_finger_words:
    enabled: true
    weight: 17.0
    normalization:
      type: weight_all
      value: 1.0
    params:
      words_filename: "./corpora/english-words-30000.csv"
      min_word_length: 3

  # Distance metric that tries to resemble the one on klanext.keyboard-design.com
  kla_distance:
    enabled: true
    weight: 0.44 # 40 weight * 0.0011 penalty * 10 ?
    normalization:
      type: weight_all
      value: 1.0
    params:
      ignore_modifiers: false
      keyup_distance: 10.5263156
      keydown_distance: 10.5263156
      dscoring:
        Left:
          Pinky: 3.67
          Ring: 2.9
          Middle: 2.0
          Index: 1.85
          Thumb: 1.0
        Right:
          Pinky: 3.67
          Ring: 2.9
          Middle: 2.0
          Index: 1.85
          Thumb: 1.0

      hscoring:
        Left: 1.1
        Right: 1.0

  # Finger usage metric that tries to resemble one from an older version of klanext
  kla_finger_usage:
    enabled: false
    weight: 1
    normalization:
      type: weight_all
      value: 1.0
    params:
      ignore_modifiers: false
      fscoring:
        Left:
          Pinky: 3.67
          Ring: 2.9
          Middle: 2.0
          Index: 1.85
          Thumb: 1.0
        Right:
          Pinky: 3.67
          Ring: 2.9
          Middle: 2.0
          Index: 1.85
          Thumb: 1.0

      hscoring:
        Left: 1.1
        Right: 1.0

  # Same finger metric that tries to resemble the one on klanext.keyboard-design.com
  kla_same_finger:
    enabled: true
    weight: 490.2 # 40 weight * 1.23 penalty * 10 ?
    normalization:
      type: weight_all
      value: 1.0
    params:
      ignore_modifiers: false
      fscoring:
        Left:
          Pinky: 3.67
          Ring: 2.9
          Middle: 2.0
          Index: 1.85
          Thumb: 1.0
        Right:
          Pinky: 3.67
          Ring: 2.9
          Middle: 2.0
          Index: 1.85
          Thumb: 1.0

      hscoring:
        Left: 1.1
        Right: 1.0

  # Same hand metric that tries to resemble the one on klanext.keyboard-design.com
  kla_same_hand:
    enabled: true
    weight: 68.2 # 20 weight * 0.341 penalty * 10 * 0.5?
    normalization:
      type: weight_all
      value: 1.0
    params:
      ignore_modifiers: false
      ignore_thumbs: false
      hscoring:
        Left: 1.1
        Right: 1.0

  # trigram metrics

ngrams:
  # Increase the weight of bigrams that have both an absolute weight and relative weight exceed
  # specified thresholds.
  increase_common_ngrams:
    enabled: false
    # Bigrams with a relative weight exceeding this threshold are considered
    critical_fraction: 0.001
    # The weight for bigrams exceeding both thresholds is multiplied by this factor
    factor: 2.0
    # Bigrams with an absolute weight exceeding this threshold are considered
    total_weight_threshold: 20.0

ngram_mapper:
  # Exclude ngrams that contain a line break, followed by a non-line-break character.
  # This encodes a mental pause which usually comes after hitting the "Enter" key, before
  # continuing to write.
  exclude_line_breaks: false

  # Split symbols belonging to higher layers of the layout into combinations involving modifiers
  # required to activate the layer
  split_modifiers:
    enabled: false
    # Multiply the ngram's weight with this factor whenever the resulting ngram involves two
    # modifiers that are required for the same symbol
    same_key_mod_factor: 0.03125
